name: variantmosaic
channels:
  - bioconda
  - plotly
dependencies:
  - python=3.10
  - bcftools=1.15
  - plotly=5.18
  - nextflow=23.10  # Optional runtime
  - vcf-kit=0.2.6   # Multi-tool interface
